.ebextensions/00-set-timezone.config
Dockerfile
build.gradle
src/main/resources/static/index.html

develop -> master

---

.github/workflows/musicalender-docker-image.yml
build.gradle
src/main/java/Musicalender/musicalenderproject/MusicalenderProjectApplication.java

master -> develop

---

.github/workflows/musicalender-docker-image.yml

workflow 수정

---

settings.gradle
src/main/java/Musicalendar/musicalendarproject/MusicalendarProjectApplication.java
src/test/java/Musicalendar/musicalendarproject/MusicalendarProjectApplicationTests.java

Musicalendar 프로젝트명 수정

---

src/main/java/Musicalendar/musicalendarproject/domain/BookMark.java
src/main/java/Musicalendar/musicalendarproject/domain/Category.java
src/main/java/Musicalendar/musicalendarproject/domain/Member.java
src/main/java/Musicalendar/musicalendarproject/domain/PersonalShow.java
src/main/java/Musicalendar/musicalendarproject/domain/Show.java
src/main/java/Musicalendar/musicalendarproject/domain/ShowSchedule.java
src/main/java/Musicalendar/musicalendarproject/domain/Site.java
src/main/java/Musicalender/musicalenderproject/domain/Category.java
src/main/resources/application-ebprod.yml

테이블 create->update 변경 & 패키지 이동

테이블 create->update 변경 & 패키지 이동

---

src/main/java/Musicalendar/musicalendarproject/domain/ImageEntity.java
src/main/java/Musicalendar/musicalendarproject/domain/ShowSchedule.java
src/main/java/Musicalendar/musicalendarproject/domain/SiteEntity.java
src/main/java/Musicalendar/musicalendarproject/service/ShowService.java
src/main/resources/application.properties

(ShowSchedule-image, site) 값타입 컬렉션->일대다 엔티티 수정

(ShowSchedule-image, site) 값타입 컬렉션->일대다 엔티티 수정

---

src/main/java/Musicalendar/musicalendarproject/HelloController.java

프론트-백 서버 연동 테스트용 코드

---

src/main/java/Musicalendar/musicalendarproject/domain/Site.java

Site에 인터파크티켓토핑 추가

---

src/main/java/Musicalendar/musicalendarproject/controller/ShowScheduleController.java
src/main/java/Musicalendar/musicalendarproject/domain/ShowRepository.java
src/main/java/Musicalendar/musicalendarproject/domain/ShowScheduleRepository.java
src/main/java/Musicalendar/musicalendarproject/service/ShowScheduleService.java

ShowSchedule GET 테스트용 코드 추가

---

src/main/java/Musicalendar/musicalendarproject/controller/ShowScheduleController.java

getAllSchedules 테스트

---

src/main/java/Musicalendar/musicalendarproject/controller/ShowScheduleController.java

getAllSchedules 테스트 2

---

src/main/java/Musicalendar/musicalendarproject/controller/ShowScheduleController.java
src/main/java/Musicalendar/musicalendarproject/repository/ShowRepository.java
src/main/java/Musicalendar/musicalendarproject/repository/ShowScheduleRepository.java
src/main/java/Musicalendar/musicalendarproject/service/ShowScheduleService.java

getmapping test

---

src/main/java/Musicalendar/musicalendarproject/controller/ShowScheduleController.java
src/main/java/Musicalendar/musicalendarproject/service/ShowScheduleService.java

getAllSchedules 테스트 수정

---

src/main/resources/application.properties

application.properties 수정

---

src/main/java/Musicalendar/musicalendarproject/domain/ShowSchedule.java

fetch LAZY 추가

---

src/main/resources/application.properties

spring.mvc.hiddenmethod.filter.enabled=true 추가

spring.mvc.hiddenmethod.filter.enabled=true 추가

---

src/main/java/Musicalendar/musicalendarproject/controller/ShowTestController.java
src/main/java/Musicalendar/musicalendarproject/service/ShowService.java

안쓰는 부분 일단 주석처리

---

src/main/resources/application.properties

spring.jpa.properties.hibernate.dialect 설정

spring.jpa.properties.hibernate.dialect 설정

---

src/main/java/Musicalendar/musicalendarproject/domain/ShowSchedule.java

OneToMany 복구

---

src/main/java/Musicalendar/musicalendarproject/domain/ShowSchedule.java

OneToMany @JsonBackReference 삭제

OneToMany @JsonBackReference 삭제

---

src/main/java/Musicalendar/musicalendarproject/domain/ShowSchedule.java

OneToMany set 타입으로 수정

---

src/main/java/Musicalendar/musicalendarproject/controller/ShowScheduleController.java
src/main/java/Musicalendar/musicalendarproject/dto/PersonalShowDto.java
src/main/java/Musicalendar/musicalendarproject/repository/PersonalShowRepository.java
src/main/java/Musicalendar/musicalendarproject/service/ShowScheduleService.java

PersonalShow post

---

src/main/java/Musicalendar/musicalendarproject/controller/ShowScheduleController.java
src/main/java/Musicalendar/musicalendarproject/service/ShowScheduleService.java

PersonalShow get
